### ISSUE TITLE
bug: getOidcConfig

### ISSUE THREAD

**Issue by zhoutaiping** [logto-io/js#396]
Module parse failed: Unexpected token (87:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class $19775a679e2952df$export$2e2bcd8739ae039 {
>     getOidcConfig = (0, $kqBTI$lodashonce)(this._getOidcConfig);
|     getJwtVerifyGetKey = (0, $kqBTI$lodashonce)(this._getJwtVerifyGetKey);
|     accessTokenMap = new Map();

 @ ./node_modules/@logto/browser/lib/module.js 1:0-378 44:22-60 55:59-77 57:30-52 70:0-347 70:0-347 70:0-347 70:0-347 70:0-347
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/views/login/index.vue?vue&type=script&lang=js&
 @ ./src/views/login/index.vue?vue&type=script&lang=js&
 @ ./src/views/login/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://172.20.1.136:4670&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by zhoutaiping** [comment]
vue2 inport

**Comment by zhoutaiping** [comment]
thanks

**Comment by charIeszhao** [comment]
@zhoutaiping As I have replied you in the [main repo ticket](https://github.com/logto-io/logto/issues/1886#issuecomment-1237727165), currently Vue 2 is not supported.
Please consider upgrading to Vue 3 or let us know if you still want to use Vue 2.
