### ISSUE TITLE
bug:  infinite loop with [watchEffect] in Vue sample code

### ISSUE THREAD

**Issue by waltcow** [logto-io/js#450]
### Describe the bug

In vue sample code

```js
watchEffect(async () => {
  if (isAuthenticated.value) {
    const userInfo = await fetchUserInfo()
    user.value = userInfo
  }
})
```

it will lead to  infinite loop

### Context

OS: 

Environment: 

Logto version: 

Node version:

Postgres version: 

Command of starting Logto:

**Comment by charIeszhao** [comment]
I'll try to reproduce and provide a fix. Will update the result ASAP.
Thanks for reporting.

**Comment by charIeszhao** [comment]
Sorry for the late response, but it seems I could not reproduce it on my side. Mind checking it out again?

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/12833674/228425226-86681586-a429-4068-8401-4a996989cb9a.png">

Thus, I'm going to close the ticket, and feel free to comment to reopen it if it still doesn't work for you.
Thanks!

**Comment by charIeszhao** [comment]
Oops... After some upgrades and I tried again, now I can reproduce it. Will look into it and provide a fix asap. Thanks for reporting
