### ISSUE TITLE
feature request: Support React Server Component

### ISSUE THREAD

**Issue by eluyuy** [logto-io/js#452]
### What problem did you meet?
React Server Component is not supported, so it cannot be used in Next.js 13 app router.

### Describe what you'd like Logto to have
Use Server Component to get user information in layout.tsx of nextjs app route

Just like [taxonomy](https://github.com/shadcn/taxonomy/blob/03ef292d26f1f96dfbd9d2773284c370e3fec7e4/app/(dashboard)/dashboard/layout.tsx#L16), by getting user information to determine whether they are logged in or not

``` typescript
export default async function DashboardLayout({children}) {
  const user = await getCurrentUser()

  if (!user) {
    return notFound()
  }

  return (
    <h1>Hello! {user.name}</h1>
  )
}
```
So maybe we can do this
``` typescript
export default async function DashboardLayout({children}) {
  const user = await logtoClient.fetchUserInfo()

  if (!user.isAuthenticated) {
    return notFound()
  }

  return (
    <h1>Hello! {user.claims.name}</h1>
  )
}
```

**Comment by gao-sun** [comment]
thanks, we are in a busy delivery cycle and will take a look after our next release (next week)

**Comment by wangsijie** [comment]
Close by https://github.com/logto-io/js/pull/487
