### ISSUE TITLE
feature request: Next13 support more usecase

### ISSUE THREAD

**Issue by waltcow** [logto-io/js#460]
Next.js data fetching methods such as [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props), [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props), and [getInitialProps](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props) are not supported in the new app directory.

- https://beta.nextjs.org/docs/data-fetching/fundamentals

### Describe what you'd like Logto to have

next13 beta integration showcase is needed

**Comment by wangsijie** [comment]
I am working on it

**Comment by waltcow** [comment]
this can be helpfully https://github.com/vvo/iron-session/issues/560

**Comment by wangsijie** [comment]
@waltcow the work is done, check this: https://github.com/logto-io/js/pull/487
