### ISSUE TITLE
bug: query userInfo with  specified scope 

### ISSUE THREAD

**Issue by waltcow** [logto-io/js#466]
### Describe the bug

when query userInfo with specified scope, response does not include the scope fields

```js
const logtoClient = new LogtoClient({
  endpoint: logtoConfig.endpoint,
  appId: logtoConfig.appId,
  appSecret: logtoConfig.appSecret,
  baseUrl: logtoConfig.baseUrl,
  cookieSecret: logtoConfig.cookieSecret,
  cookieSecure: logtoConfig.cookieSecure,
  resources: logtoConfig.resources,
  scopes: ["custom_data"],
});

export default logtoClient.handleAuthRoutes({
  fetchUserInfo: true,
});

```

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/3941174/229704885-e0bde3df-42c4-4aca-aa81-1003aadbaa06.png">

### Context

Environment:

**Comment by gao-sun** [comment]
please fulfill more context for better debugging, e.g. Logto environment, which SDK, version

**Comment by simeng-li** [comment]
The UserInfo endpoint does not return any scope-related fields. You may find the reference [here](https://docs.logto.io/docs/recipes/integrate-logto/next-js#fetch-user-info).  

You have to decode an access_token to retrieve the related scopes assigned to that token.

**Comment by waltcow** [comment]
> The UserInfo endpoint does not return any scope-related fields. You may find the reference [here](https://docs.logto.io/docs/recipes/integrate-logto/next-js#fetch-user-info).  
> 
> 
> 
> You have to decode an access_token to retrieve the related scopes assigned to that token. 
> 
> 

I just want to retrieve the custom_data field when fetch userinfo
