### ISSUE TITLE
feature request:  next13 support session context and react hook

### ISSUE THREAD

**Issue by waltcow** [logto-io/js#468]
### What problem did you meet?

https://beta.nextjs.org/docs/rendering/server-and-client-components#context

https://github.com/nextauthjs/next-auth/blob/6c07331cc53abe45c644308af6b6f2de29fdae2e/packages/next-auth/src/react/index.tsx

maybe we can provide a `sessionContext` with logto,
`useSession() ` as a React Hook  to check if someone is signed in in client component

```jsx

import { useSession, signIn, signOut } from "logto/next/react"

export default function Component() {
  const { data: session } = useSession()
  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    )
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  )
}
```

**Comment by wangsijie** [comment]
Closed by https://github.com/logto-io/js/pull/487
