### ISSUE TITLE
feature request: Edge client with decode/verify token utility 

### ISSUE THREAD

**Issue by waltcow** [logto-io/js#493]
### What problem did you meet?

In next13 app folder, we have very common situation for developer to get user cookie from `cookies()` an then decode it into session, verify/decode IDToken(unseal data from session) in js code, but the logto edge client still missing this feature

**Comment by wangsijie** [comment]
Hi, the Logto edge client was just updated, it has built-in cookies and session, and you can get IDToken by calling `logtoClient.getLogtoContext`, you can check the sample: https://github.com/logto-io/js/tree/master/packages/next-sample

**Comment by wangsijie** [comment]
@waltcow it is ready on npm: https://www.npmjs.com/package/@logto/next

**Comment by waltcow** [comment]
thanks
