### ISSUE TITLE
bug: Cannot find module '@logto/next/edge' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by eluyuy** [logto-io/js#499]
### Describe the bug
Cannot find module '@logto/next/edge' or its corresponding type declarations.ts(2307)

### Expected behavior

Importing modules without errors.

### How to reproduce?

Use "next-app-dir-sample" to change the version of "@logto/next" in packages.json dependencies to the latest version (2.1.0) published on npm. This will reproduce.

It works after import, but it does not pass the "Linting and checking validity of types"

When I moved "node_modules/@logto/next/lib/edge" to "node_modules/@logto/next/edge",  I was able to import it successfully.
I think this may be a problem caused by not export correctly?

### Context

[next-app-dir-sample](https://github.com/logto-io/js/tree/c5773294f8ab09fdbf9d23fbbed73bca15fbbb38/packages/next-app-dir-sample)

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [x] Raw Node.js

### Screenshots

![Snipaste_2023-05-23_17-54-35](https://github.com/logto-io/js/assets/118240464/6fdfe70d-e75a-4e20-b6a1-adc12252b25e)
![Snipaste_2023-05-23_17-57-38](https://github.com/logto-io/js/assets/118240464/c1d67bbb-e8d1-48a2-a730-7500f3e331f4)

**Comment by charIeszhao** [comment]
@eluyuy What's your typescript version?

**Comment by eluyuy** [comment]
@charIeszhao 5.0

**Comment by charIeszhao** [comment]
@eluyuy Hmmm, can you upload a reproducible repo so that we can dive into and try to find the root cause? Because it works on our side, and we doubt it might not need to configure "typeVersions".

**Comment by eluyuy** [comment]
> @eluyuy Hmmm, can you upload a reproducible repo so that we can dive into and try to find the root cause? Because it works on our side, and we doubt it might not need to configure "typeVersions".

@charIeszhao The problem can be reproduced using [next-app-dir-sample](https://github.com/logto-io/js/tree/c5773294f8ab09fdbf9d23fbbed73bca15fbbb38/packages/next-app-dir-sample)

@logto/next use 2.1.0 published on npm

Both Windows and Linux can be replicated
Windows (11):
node v18.15.0
pnpm v7.29.3

Linux (Ubuntu 20.04.6 LTS):
node v19.9.0
pnpm v8.3.1

**Comment by charIeszhao** [comment]
Thanks, we'll take a look
