### ISSUE TITLE
Infinite Loop Issue in Code Snippet

### ISSUE THREAD

**Issue by msmarks** [logto-io/js#501]
The following code snippet contains a potential infinite loop:

https://github.com/logto-io/js/blob/c5773294f8ab09fdbf9d23fbbed73bca15fbbb38/packages/vue/src/index.ts#L137-L147

The issue arises when `handleSignInCallback` encounters an error that causes it to consistently throw an exception. In specific cases, if the code within handleSignInCallback always sets `isLoading` to `true` when an error occurs and then sets it back to `false` in the finally block, it triggers the re-execution of the `watchEffect` function, leading to an infinite loop deadlock state on the page.

Code causing the infinite loop:

https://github.com/logto-io/js/blob/c5773294f8ab09fdbf9d23fbbed73bca15fbbb38/packages/vue/src/plugin.ts#L87-L112

The issue can be reproduced when the user is not logged in, causing `handleSignInCallback` to consistently set `loading` to `true`, followed by setting it to` false` in the finally block.
Please review and address this issue to prevent the infinite loop deadlock scenario.

**Comment by wangsijie** [comment]
@charIeszhao would you mind taking a look?

**Comment by charIeszhao** [comment]
Thanks for reporting.
