### ISSUE TITLE
Bug: Incorrect Return Value from isSignInRedirected in watchEffect

### ISSUE THREAD

**Issue by msmarks** [logto-io/js#508]
https://github.com/logto-io/js/blob/4f23bf9c2693bd2420c9df22345ef44bd00907a0/packages/vue/src/index.ts#L137-L143

The code provided in the `watchEffect` block has a bug that causes the `isSignInRedirected` function to always return true, regardless of its actual logic. This issue arises because the function `isSignInRedirected` is an async function and is called without awaiting its execution.

**Comment by charIeszhao** [comment]
Thanks for reporting. This is a critical bug and should've been noticed earlier.
