### ISSUE TITLE
Can't resolve 'crypto'

### ISSUE THREAD

**Issue by HighError** [logto-io/js#517]
### Describe the bug
Module not found: Can't resolve 'crypto' when I create /api/sign-in/route.ts and copy the code from the example.
Expected 2 arguments, but got 1 for `return logtoClient.handleSignIn()(request);`

### How to reproduce?
Follow the instructions https://docs.logto.io/docs/recipes/integrate-logto/next-js-13/

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 1.5.0
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

![image](https://github.com/logto-io/js/assets/46526245/7bb66292-a31f-4cc9-9814-838f20330124)
![image](https://github.com/logto-io/js/assets/46526245/47015b80-bccf-48da-bda4-de03bb86ebb2)

**Comment by HighError** [comment]
![image](https://github.com/logto-io/js/assets/46526245/388ac0f1-7837-470c-8937-25df1d85ff44)
![image](https://github.com/logto-io/js/assets/46526245/0c0fb809-4539-4c2a-bfb3-f8ce7892c69e)

**Comment by wangsijie** [comment]
What is the runtime of the Next.js server? If your runtime is edge-like, it may not support `cyrpto`, in this case, you can try [the edge sdk](https://docs.logto.io/docs/recipes/integrate-logto/next-js/#edge-runtime)

**Comment by HighError** [comment]
oh sorry, i import "logto/next", not @logto/next/edge. 
I trusted the IDE
