### ISSUE TITLE
bug: support LTS Node.js

### ISSUE THREAD

**Issue by David-van-der-Sluijs** [logto-io/js#613]
When using the latest LTS Node.js version (v20.11.0) the `npm install` command fails:

```bash
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @silverhand/essentials@2.8.6
npm ERR! notsup Not compatible with your version of node/npm: @silverhand/essentials@2.8.6
npm ERR! notsup Required: {"node":"^16.13.0 || ^18.12.0 || ^19.2.0","pnpm":"^8.0.0"}
npm ERR! notsup Actual:   {"npm":"10.3.0","node":"v20.11.0"}
```

**Comment by charIeszhao** [comment]
Thanks for the feedback. We'll take a look and keep you updated

**Comment by charIeszhao** [comment]
This should have been fixed in the latest version. It's been releasing now to the NPM. Please wait for a minutes and check it out.
Let us know if you have other issues. Cheers!

**Comment by David-van-der-Sluijs** [comment]
Thank you very much for the speedy fix! I can indeed confirm it installs now without a problem.

**Comment by Jogai** [comment]
Why restrict it to lts? Just a minimum should be enough I'd think.
