### ISSUE TITLE
bug: replace CommonJS 'camelcase-keys' dependency

### ISSUE THREAD

**Issue by David-van-der-Sluijs** [logto-io/js#618]
When using this library inside an angular application, the compiler warns about a CommonJS dependency used here:

```bash
Warning: node_modules/@logto/js/lib/core/fetch-token.js depends on 'camelcase-keys'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

I think that is a rather simple library that could be either replaced or the functionality written from scratch.
If I have the time, I can look into it further and suggest something / write something.

**Comment by xiaoyijun** [comment]
Tracked in LOG-8216.

**Comment by gao-sun** [comment]
it's 2024, we can update our SDKs to ESM-only

**Comment by charIeszhao** [comment]
How about this one? [change-case](https://github.com/blakeembrey/change-case) @gao-sun
