### ISSUE TITLE
feature request: angular example with more usecase, such as multiple resources?

### ISSUE THREAD

**Issue by lonelyhentxi** [logto-io/js#656]
### What problem did you meet?

It seems like the [angular-example](https://github.com/logto-io/js/blob/master/packages/angular-sample/src/app/app.config.ts) only supports one resource to be passed. And then I tried to call the login/logout methods like the example, while call `getAccessTokenClaims` from the bare `LogToClient` to get the scopes at the same time, but it failed to grant, maybe as they are using different storage and keys?

### Describe what you'd like Logto to have

Could you please give more details about using logto (with multi-resources) and angular? Or  provide a Angular SDK like VueJS directly?

**Comment by gao-sun** [comment]
Since the Angular sample isn't using Logto JS client, it'll be tricky to support multiple resources. We can add an Angular SDK shortly.

**Comment by charIeszhao** [comment]
We now support passing resources in a single string with comma as separator (https://github.com/logto-io/logto/pull/5773), so I think this may make it possible for you to do it in Angular.
Let me know if this works

**Comment by lonelyhentxi** [comment]
> We now support passing resources in a single string with comma as separator ([logto-io/logto#5773](https://github.com/logto-io/logto/pull/5773)), so I think this may make it possible for you to do it in Angular. Let me know if this works

Thanks, works fine now. I will close the issue. Still it would be better if there is a official angular SDK that support the ability to request both user info and API resource access tokens.

**Comment by charIeszhao** [comment]
Thanks for the update. The Angular SDK is on our roadmap. Please stay tuned to our future updates.
