### ISSUE TITLE
feature request: remixjs support signUp instead of just sign in

### ISSUE THREAD

**Issue by samos123** [logto-io/js#722]
I want to have a login and sign up button using remixjs, however remix only supports sign in flow. The request is to also add a sign up handler into the logto/remix SDK

I noticed that in NextJS you can already set InteractionModel, which is what I would like to also be able to do in RemixJS.

See nextjs example: https://github.com/logto-io/js/blob/master/packages/next/src/index.ts#L55

Express JS example: https://github.com/logto-io/js/blob/master/packages/express/src/index.ts#L79

context from discord: https://discord.com/channels/965845662535147551/1241584329331839030/1241584331575529563

**Comment by darcyYe** [comment]
Hi @samos123 , Remix SDK is contributed and maintained by our community. It is somehow outdated, for support on `interactionMode` props, you are welcomed to contribute if it is now in urgent. Here is a PR that support this feature in other SDKs, which should be helpful.
If you have any difficulties, you can leave a message here or join Discord server to get a timely reply.

**Comment by samos123** [comment]
Thank you. I will give it a try

**Comment by charIeszhao** [comment]
The new release v2.2.0 is available now. Thank you for your contribution.
