### ISSUE TITLE
bug: Not able to set redirect URL for NuxtJS Module.

### ISSUE THREAD

**Issue by funkel1989** [logto-io/js#763]
### Describe the bug
The @logto/nuxt module does not allow a custom redirect URL. I need this because my nuxtjs site is hosted with its server on aws lambda backed by api gateway and its static content on an s3 bucket. This is brought together with both origins in aws cloudfront. Bottom line is, the code currently gets redirect URL via the HREF and thats happening on the server which means the callback URL is to the URL of the API gateway which doesn't have a cert on it and doesn't actually host the entire frontend. I need to be able to tell it that its URL is that of the actual website URL to the callback passes through cloudfront and gets correctly routed.

### Expected behavior
I'd like to be able to pass in a redirectURL that is expected by my site.

### How to reproduce?
Look at your exported type and Code, this is not allowed the way it is currently written

### Context
- [X] Logto Cloud
- [ ] Self-hosted
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by funkel1989** [comment]
FYI I'm more than happy to submit a PR to add redirectUri as a parameter that can override what is currently in the settings but I need some context on why you opted to go the way you did because it looks like most/all of the different js packages work the same way.

**Comment by wangsijie** [comment]
I believe the Next.js SDK has a configuration option called `baseUrl` that might address your issue. If Nuxt.js SDK has a similar option, it could potentially solve your problem. I've reviewed your pull request, and it looks promising. Perhaps we could simplify the naming by changing `baseUrlOverride` to just `baseUrl`, similar to the Next.js implementation.

https://github.com/logto-io/js/blob/master/packages/next/src/index.ts#L74

**Comment by wangsijie** [comment]
I am closing this now because https://github.com/logto-io/js/pull/793 has resolved this, feel free to reopen if you have any further questions
