### ISSUE TITLE
bug: @logto/nuxt package is blocking Nuxt prerender function.

### ISSUE THREAD

**Issue by kgierke** [logto-io/js#770]
### Describe the bug

At the moment the `@logto/nuxt` module is throwing an error if the configuration keys haven't been changed. Therefore using `prerenderer` or `@nuxt/content` is not possible if no values have been provided.

### Expected behavior

Nuxt build should work without problems.

### How to reproduce?

Install `@logto/nuxt` and `@nuxt/content` and try to build the project without providing the configuration values.

### Context

I think the error should rather be a warning so it isn't preventing Nuxt from building the application.

In a Docker context where the variables are set during runtime and not at build time it shouldn't be necessary to provide the logto configuration keys.

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by wangsijie** [comment]
Hi @kgierke, I've successfully reproduced the error you reported. Thank you for bringing this to our attention. I'll discuss with the team about changing it as a "warning" instead.
