### ISSUE TITLE
feature request: How to set the directSignIn property in the singin function Using useLogto

### ISSUE THREAD

**Issue by soralee** [logto-io/js#777]
### What problem did you meet?

I am using the useLogto hook in my React application and I would like to know if it is possible to set the signIn function to enable the directSignIn property. 

### Describe what you'd like Logto to have

Could you please provide guidance or an example on how to achieve this?

**Comment by darcyYe** [comment]
You can take a look on our [direct sign-in docs](https://docs.logto.io/docs/references/openid-connect/authentication-parameters/#direct-sign-in) to see if it can help. We currently do not have a guide for direct sign-in, but we are going to work on providing guide and update SDK to boost developers experience.

**Comment by charIeszhao** [comment]
If you are using React SDK, try this;
```ts
<button
  type="button"
  onClick={() => {
    void signIn({
      redirectUri,
      directSignIn: { method: 'social', target: 'google' },
    });
  }}
>
  Sign in
</button>
```

**Comment by soralee** [comment]
Thanks for all the replies. 
I realized the issue was a TypeScript error on my part, and updating to version 3.0.14 resolved it. 

I'll close this now.

Thanks again for all the help!
