### ISSUE TITLE
bug: isAuthenticated is always true even when session is expired

### ISSUE THREAD

**Issue by Hanmo123** [logto-io/js#835]
### Describe the bug

I am using @logto/vue and my session is expired(the response of logto is 400), but the return value of logto.isAuthenticated is still true

### Expected behavior

It should be false.

### How to reproduce?

Just wait for session to be expired.

### Context

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

![image](https://github.com/user-attachments/assets/1621ad40-11f8-45a0-91dc-6e982a801ad7)

**Comment by wangsijie** [comment]
`isAuthenticated` is true if a sign-in state exists locally. For accurate results, communicate with the remote server (Logto) by calling `getAccessToken` or fetching the user information.

**Comment by Hanmo123** [comment]
It's a little counterintuitive, maybe it can be improved.

**Comment by wangsijie** [comment]
should not depend on the client to accurately determine the actual authentication status.
