### ISSUE TITLE
bug: next.js 15 cookies is async function

### ISSUE THREAD

**Issue by dipakparmar** [logto-io/js#836]
### Describe the bug

The current implementation of `client.ts` uses cookies as synchronous functions, which is incompatible with Next.js 15 and later. In Next.js 15, the `cookies` object provides asynchronous methods for accessing and manipulating cookies.

### Expected behavior

The `client.ts` code should be updated to use the asynchronous cookie methods introduced in Next.js 15. This will ensure compatibility with the latest versions of Next.js and prevent errors when accessing or manipulating cookies.

### How to reproduce?

1.  Use Logto JS SDK in a Next.js 15 project.
2.  Attempt to access or manipulate cookies using the `logto` client.
3.  Observe errors related to cookies being accessed synchronously.

### Context

- Self-hosted, Logto version = 
  - [x] Container (Docker image) 
  - [x] Raw Node.js - 20.x.x

### Additional context

I believe the following code snippet from [packages/next/server-actions/client.ts](https://github.com/logto-io/js/blob/3085378d618dbb9a3aa37f293da4cf2c2f1266f2/packages/next/server-actions/client.ts#L112) needs to be updated:

Next.js 15 cookies API reference: [https://nextjs.org/docs/app/api-reference/functions/cookies](https://nextjs.org/docs/app/api-reference/functions/cookies)

**Comment by l4b4r4b4b4** [comment]
@wangsijie Cheers for picking this up! :pray:

**Comment by l4b4r4b4b4** [comment]
any progress on this? :nose:  ;)

**Comment by alishahlakhani** [comment]
Yess please! any update on this? @wangsijie

**Comment by wangsijie** [comment]
I'll upgrade this soon.
