### ISSUE TITLE
feature request: Project startup documentation required

### ISSUE THREAD

**Issue by ByZhouhang** [logto-io/js#841]
I am a back-end developer, focusing on projects that separate front-end and back-end. Now I want to run a front-end demo test ， but I find that I can't get started. Can the official provide some documentation?

**Comment by michaelgiraldo** [comment]
That already exists it’s our private cloud offering for enterprise customers.

**Comment by charIeszhao** [comment]
Check our quick-start documentations first: https://docs.logto.io/quick-starts/

We have all mainstream front-end frameworks coveredl. Let us know if you need something else.
