### ISSUE TITLE
bug:  @logto/nuxt does not hook into the Nuxt router, thus breaking programmatical navigation to login and logout pages

### ISSUE THREAD

**Issue by Stax124** [logto-io/js#848]
### Describe the bug
Nuxt developers can use `useRouter` for easy navigation to a different page. This totally skips the logic defined by @logto/nuxt and just goes to HTTP404 page instead, as this page was not found in the `pages/` directory

### Expected behavior
Developers can use `router.push("/auth/login")` or similar to easily navigate to the Logto sign-in (or sign-out) page

### How to reproduce?
 - Create a basic Nuxt application
 - Install @logto/nuxt package and set it up
 - Create a page with a button that uses `router.push` method instead of `<a>` element
 - Nuxt crashes with 404 page not found instead of triggering the hook to redirect to Logto page
 - Reload the site - triggering full page refresh should trigger the hook and get you to the Logto page as expected

### Context
- @logto/nuxt: v1.0.1
- Nuxt: v3.14.0

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### References

- https://github.com/logto-io/js/blob/master/packages/nuxt/src/runtime/server/event-handler.ts

### Possible solutions

- Hook `router.beforeEach` method as well

```ts
import { defineNuxtModule, extendRouteRules } from '@nuxt/kit'

export default defineNuxtModule({
  setup(options) {
    extendRouteRules('/login', {
      redirect: {
        to: 'target-logto-url',
        statusCode: 302
      }
    })
  }
})
```

**Comment by xiaoyijun** [comment]
@wangsijie would you like to take a look at this nuxt issue?

**Comment by zguiyang** [comment]
I experienced the same problem.

**Comment by wangsijie** [comment]
That is because, `router.push` does not trigger the event listener:

```ts
addServerHandler({
  handler: resolve('./runtime/server/event-handler'),
});
```

Trying to find a solution.

**Comment by wangsijie** [comment]
`router.push` won’t trigger the server handler, so we recommend using an `<a>` tag instead. However, after this [PR](https://github.com/logto-io/js/pull/892), you can access `logtoEventHandler` to customize the behavior as needed. If you still prefer using router.push, you can manually initialize Logto to ensure proper functionality.
