### ISSUE TITLE
feature request:  @logto/nuxt export EventHandler

### ISSUE THREAD

**Issue by 0721-Day** [logto-io/js#850]
### What problem did you meet?
I hope @ logto/nuxt can export EventHandler

### Describe what you'd like Logto to have
I need to obtain the userinfo of logot when using middleware

I found that when using middleware, I couldn't get Userinfo from event.context, but I could get it during API processing.
So after testing, I can create a timeout to retrieve it.
I can also extract the event handler and manually register it as "0. logo. ts", which can run normally.

**Comment by 0721-Day** [comment]
Perhaps it's just my lack of skills. I hope all the experts can give me some guidance. Thank you

**Comment by charIeszhao** [comment]
More context would be appreciated. Maybe you can even share some of your code to help us better understand your request.

**Comment by 0721-Day** [comment]
When I use @ logto/nuxt
I created 0001. a.ts on server/middleware/
` export default defineEventHandler(async (event) => {
    console.log(event.context)
  })`
I requested any page, and its result is ` {_nitro: {routeRules: {}}}, nitro: {errors: []}}}`
Logto is not running, but I can retrieve the results of Logto from the route.

I tried to add @ logto/nuxt to modules later, but the result remained unchanged.

Then.
 I created 0000. logto.ts on server/middleware/
 `export * from "@/modules/logto/runtime/server/event-handler"`
 
You can see logtoClient in the output of 0001. a.ts
![image](https://github.com/user-attachments/assets/a1339248-dede-481e-9480-a81756c1a39b)

I tried other methods, such as adding 'middleware: true' in addServerHandler, but I couldn't get logtoClient from the middleware

**Comment by wangsijie** [comment]
@0721-Day please check this PR: https://github.com/logto-io/js/pull/892

You can use it in server middleware. (not normal middleware which does not have "event")
