### ISSUE TITLE
await cookies

### ISSUE THREAD

**Issue by Dakuan** [logto-io/js#851]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@logto/next@3.7.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@logto/next/lib/server-actions/client.js b/node_modules/@logto/next/lib/server-actions/client.js
index 09129a6..d44bdd9 100644
--- a/node_modules/@logto/next/lib/server-actions/client.js
+++ b/node_modules/@logto/next/lib/server-actions/client.js
@@ -64,13 +64,13 @@ class LogtoClient extends LogtoNextBaseClient {
             encryptionKey: this.config.cookieSecret,
             cookieKey: `logto:${this.config.appId}`,
             isSecure: this.config.cookieSecure,
-            getCookie: (...args) => {
-                return cookies().get(...args)?.value ?? '';
+            getCookie: async (...args) => {
+                return (await cookies()).get(...args)?.value ?? '';
             },
-            setCookie: (...args) => {
+            setCookie: async (...args) => {
                 // In server component (RSC), it is not allowed to modify cookies, see https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options.
                 if (!ignoreCookieChange) {
-                    cookies().set(...args);
+                    (await cookies()).set(...args);
                 }
             },
         });
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by charIeszhao** [comment]
@wangsijie Do you think the await is necessary? Are cookies async?

**Comment by Dakuan** [comment]
yes 

```[Error: Route "/" used `cookies().get('logto:jwtsdep1memhjojskp0fk')`. `cookies()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis]```

**Comment by Dakuan** [comment]
terminal looks like this in next 15 😂

![image](https://github.com/user-attachments/assets/49513866-9f6d-46a9-b306-6fed2f85d3a5)

**Comment by wangsijie** [comment]
https://github.com/logto-io/js/issues/836

**Comment by kdy1** [comment]
Next.js maintainer & logto (personal) user here. This is the change in next@15

See https://nextjs.org/docs/app/building-your-application/upgrading/version-15#async-request-apis-breaking-change for more details.
