### ISSUE TITLE
bug: Firefox reload loop app using @logto/react useHandleSignInCallback and signIn

### ISSUE THREAD

**Issue by harlott** [logto-io/js#852]
### Describe the bug
I'm using @logto/react in a webapp.
The integration works fine into Chrome, but Firefox send it in reload loop, after my self-hosted logto server login, using useHandleSignInCallback and signin logto methods.
I've followed the integration react example; i've disabled, for development purpose, all protection settings, clear cache etc in Firefox; i've enabled cross-origin in logto server, but nothing fixes the issue

### Expected behavior
Same app behavior in Firefox/Brave/Chrome 

### How to reproduce?
1) Delete all local data;
2) Load the app: it will redirect the app to login form page;
3) Successfully sign in with credentials;
4) On callback page, the app will reload the page refreshing the code in query string

### Context

- [ ] Logto Cloud
- [x ] Self-hosted, Logto version = v1.22.0 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
App.jsx

![image](https://github.com/user-attachments/assets/53c09045-9cea-42d3-b907-5e6500ed5a7d)

RequireAuth.jsx

![image](https://github.com/user-attachments/assets/71893b6a-cf48-418d-a3b7-df69fefdfff3)

SigninCallback.jsx

![image](https://github.com/user-attachments/assets/f603a09e-158d-4f57-9a5c-ab3f2585cf55)

**Comment by simeng-li** [comment]
Can you provide the detailed error logs?

**Comment by harlott** [comment]
> Can you provide the detailed error logs?

Only one error, simply the first POST to logto server is interrupted by Firefox:

![image](https://github.com/user-attachments/assets/c2efd541-daf8-4107-b1bc-c5b79ee5cb54)

**Comment by KevinLeneschmidt** [comment]
I am also stuck in a loop using @logto/browser and the latest version of logto in a docker container. It appeared randomly while I didn't change anything.

**Comment by KevinLeneschmidt** [comment]
> I am also stuck in a loop using @logto/browser and the latest version of logto in a docker container. It appeared randomly while I didn't change anything.

I actually cleared my docker stuff before and forgot to run my db migrations... After i ran them, everything works fine again. I wasted so many hours on debugging this... xD

**Comment by wangsijie** [comment]
It looks like the issue has been resolved, I am closing this now, feel free to reopen.
