### ISSUE TITLE
bug: Sign-in session not found after upgrading to @logto/next higher than 3.5.0

### ISSUE THREAD

**Issue by SamSalvatico** [logto-io/js#888]
### Describe the bug
I'm working on a NextJs application and I'm having troubles using the new @logto/next library version migrating from the V3.5.0

These are the different deps I am using:
Next v14
@logto/next V4.10
Logto Open Source v1.20

This is the code where the error is thrown
```
import { handleSignIn } from "@logto/next/server-actions"
import { redirect } from "next/navigation"
import type { NextRequest } from "next/server"
import { getSignInConfiguration } from "../../utils/logto-config"

export async function GET(request: NextRequest) {
  await handleSignIn(getSignInConfiguration(), request.nextUrl.searchParams)

  redirect("/")
}
```

This is the error: 
```
 ⨯ LogtoClientError: Sign-in session not found.
[0] [4]     at #handleSignInCallback (webpack-internal:///(rsc)/../../node_modules/@logto/client/lib/client.js:385:19)
```

I've tried with multiple browsers, with a clean state

I've noticed that the way the session cookie is stored changed between the two versions: https://github.com/logto-io/js/compare/%40logto/next%403.5.0...%40logto/next%404.1.0#diff-900af175a5b3e1bcadf86020dd3e1a5ab39c345a2cf8b0b3fa548bd979b4f847L117

Maybe it could help

### Expected behavior
Callback finds the session after login and make user able to login

### How to reproduce?

[This](https://github.com/ogcio/life-events/blob/dev/apps/messaging/app/%5Blocale%5D/callback/route.ts) is the code where the error is thrown

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = v1.20
  - [x] Container (Docker image)
  - [x] Raw Node.js

**Comment by wangsijie** [comment]
The latest SDK (v4.1.0) is compatible with Next.js 15, which introduces some breaking changes. For details, refer to https://nextjs.org/blog/next-15. We recommend upgrading to Next.js 15 for the best experience.

If you prefer to stick with Next.js 14, it’s safer to continue using the older version of the SDK (v3.x).

**Comment by SamSalvatico** [comment]
Okay for the v4.1.0, but for the 3.7.1 the error is the same, that's why I thought that the cookie encryption method was the cause of the issue
